version: 2
updates:
  - package-ecosystem: cargo # zizmor: ignore[dependabot-cooldown] # Unless dependencies are pinned/locked, the effect is limited.
    directories:
      - /
      # crates with [workspace] table are not recognized by the above 'directory: /'
      - /tests/fixtures/crates/trybuild
      - /tests/fixtures/crates/ui_test
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    labels: []
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    commit-message:
      prefix: ''
    labels: []
