name: Release

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to be increased
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

jobs:
  release:
    if: github.repository_owner == 'taiki-e'
    uses: taiki-e/github-actions/.github/workflows/rust-release.yml@main
    permissions:
      contents: write # for taiki-e/create-gh-release-action / taiki-e/upload-rust-binary-action
      id-token: write # for rust-lang/crates-io-auth-action / actions/attest
      attestations: write # for actions/attest
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      bin: cargo-llvm-cov
      # -C instrument-coverage doesn't support aarch64-pc-windows-msvc yet (https://github.com/rust-lang/rust/issues/150123),
      # but cross-compile to aarch64-pc-windows-gnullvm works.
      # Skip x86_64-unknown-illumos because it doesn't support -C instrument-coverage: error[E0463]: can't find crate for `profiler_builtins`
      # Skip s390x-unknown-linux-musl because it's tier 3
      bin-target: |
        aarch64-unknown-linux-gnu
        aarch64-unknown-linux-musl
        aarch64-apple-darwin
        aarch64-pc-windows-msvc
        x86_64-unknown-linux-gnu
        x86_64-unknown-linux-musl
        x86_64-apple-darwin
        x86_64-pc-windows-msvc
        x86_64-unknown-freebsd
        universal-apple-darwin
        powerpc64le-unknown-linux-gnu
        powerpc64le-unknown-linux-musl
        riscv64gc-unknown-linux-gnu
        riscv64gc-unknown-linux-musl
        s390x-unknown-linux-gnu
